version: "2"
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - gosec
    - govet
    - ineffassign
    - nestif
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    gosec:
      excludes:
        - G109
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'SA1019:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/openshift
        - github.com/metal3-io
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
