/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openshift/cluster-baremetal-operator/apis/metal3.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProvisionings implements ProvisioningInterface
type FakeProvisionings struct {
	Fake *FakeMetal3V1alpha1
}

var provisioningsResource = schema.GroupVersionResource{Group: "metal3.io", Version: "v1alpha1", Resource: "provisionings"}

var provisioningsKind = schema.GroupVersionKind{Group: "metal3.io", Version: "v1alpha1", Kind: "Provisioning"}

// Get takes name of the provisioning, and returns the corresponding provisioning object, and an error if there is any.
func (c *FakeProvisionings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Provisioning, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(provisioningsResource, name), &v1alpha1.Provisioning{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Provisioning), err
}

// List takes label and field selectors, and returns the list of Provisionings that match those selectors.
func (c *FakeProvisionings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProvisioningList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(provisioningsResource, provisioningsKind, opts), &v1alpha1.ProvisioningList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProvisioningList{ListMeta: obj.(*v1alpha1.ProvisioningList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProvisioningList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested provisionings.
func (c *FakeProvisionings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(provisioningsResource, opts))
}

// Create takes the representation of a provisioning and creates it.  Returns the server's representation of the provisioning, and an error, if there is any.
func (c *FakeProvisionings) Create(ctx context.Context, provisioning *v1alpha1.Provisioning, opts v1.CreateOptions) (result *v1alpha1.Provisioning, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(provisioningsResource, provisioning), &v1alpha1.Provisioning{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Provisioning), err
}

// Update takes the representation of a provisioning and updates it. Returns the server's representation of the provisioning, and an error, if there is any.
func (c *FakeProvisionings) Update(ctx context.Context, provisioning *v1alpha1.Provisioning, opts v1.UpdateOptions) (result *v1alpha1.Provisioning, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(provisioningsResource, provisioning), &v1alpha1.Provisioning{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Provisioning), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProvisionings) UpdateStatus(ctx context.Context, provisioning *v1alpha1.Provisioning, opts v1.UpdateOptions) (*v1alpha1.Provisioning, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(provisioningsResource, "status", provisioning), &v1alpha1.Provisioning{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Provisioning), err
}

// Delete takes name of the provisioning and deletes it. Returns an error if one occurs.
func (c *FakeProvisionings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(provisioningsResource, name), &v1alpha1.Provisioning{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProvisionings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(provisioningsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProvisioningList{})
	return err
}

// Patch applies the patch and returns the patched provisioning.
func (c *FakeProvisionings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Provisioning, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(provisioningsResource, name, pt, data, subresources...), &v1alpha1.Provisioning{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Provisioning), err
}
