apiVersion: v1
kind: ConfigMap
metadata:
  name: baremetal-kube-rbac-proxy
  namespace: openshift-machine-api
  annotations:
    capability.openshift.io/name: baremetal
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
data:
  config-file.yaml: |+
    authorization:
      resourceAttributes:
        apiVersion: v1
        resource: namespace
        subresource: metrics
        namespace: openshift-machine-api

