apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: baremetal
  annotations:
    capability.openshift.io/name: baremetal
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec: {}
status:
  versions:
  - name: operator
    version: "0.0.1-snapshot"
  relatedObjects:
  - group: ""
    name: openshift-machine-api
    resource: namespaces
  - group: "metal3.io"
    name: ""
    resource: "baremetalhosts"
    namespace: openshift-machine-api
  - group: "metal3.io"
    name: ""
    resource: "provisioning"
  - group: "metal3.io"
    name: ""
    resource: "hostfirmwaresettings"
    namespace: openshift-machine-api
  - group: "metal3.io"
    name: ""
    resource: "firmwareschemas"
    namespace: openshift-machine-api
  - group: "metal3.io"
    name: ""
    resource: "preprovisioningimages"
    namespace: openshift-machine-api
  - group: "metal3.io"
    name: ""
    resource: "bmceventsubscriptions"
    namespace: openshift-machine-api
  - group: "metal3.io"
    name: ""
    resource: "hostfirmwarecomponents"
    namespace: openshift-machine-api
  - group: "metal3.io"
    name: ""
    resource: "dataimages"
    namespace: openshift-machine-api
  - group: "metal3.io"
    name: ""
    resource: "hostupdatepolicies"
    namespace: openshift-machine-api