apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    capability.openshift.io/name: baremetal
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: cluster-baremetal-operator
  namespace: openshift-machine-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    capability.openshift.io/name: baremetal
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: baremetal-operator
  namespace: openshift-machine-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    capability.openshift.io/name: baremetal
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: metal3
  namespace: openshift-machine-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    capability.openshift.io/name: baremetal
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: metal3-image-customization
  namespace: openshift-machine-api
---
