apiVersion: v1
kind: Service
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    service.alpha.openshift.io/serving-cert-secret-name: cluster-baremetal-operator-tls
  labels:
    k8s-app: cluster-baremetal-operator
  name: cluster-baremetal-operator-service
  namespace: openshift-machine-api
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    k8s-app: cluster-baremetal-operator
  sessionAffinity: None
  type: ClusterIP
