apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
  labels:
    k8s-app: cluster-baremetal-operator
  name: cluster-baremetal-operator-servicemonitor
  namespace: openshift-machine-api
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: cluster-baremetal-operator.openshift-machine-api.svc
  namespaceSelector:
    matchNames:
    - openshift-machine-api
  selector:
    matchLabels:
      k8s-app: cluster-baremetal-operator
