apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metal3-image-customization
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - preprovisioningimages
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - preprovisioningimages/status
  verbs:
  - get
  - patch
  - update
