apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-baremetal-operator
  namespace: openshift-machine-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: baremetal-operator
  namespace: openshift-machine-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metal3
  namespace: openshift-machine-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metal3-image-customization
  namespace: openshift-machine-api
