commonAnnotations:
  include.release.openshift.io/self-managed-high-availability: "true"
  include.release.openshift.io/single-node-developer: "true"
  capability.openshift.io/name: baremetal

resources:
- cluster-baremetal-operator.yaml
