// Code generated by go-bindata. (@generated) DO NOT EDIT.

//Package testdata generated by go-bindata.// sources:
// testdata/bindata.go
// testdata/bmh-secret.yaml
// testdata/bmh.yaml
// testdata/firmware-cm.yaml
// testdata/fixtures.go
// testdata/host-update-policy.yaml
// testdata/nginx-firmware.yaml
package testdata

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _bindataGo = []byte(``)

func bindataGoBytes() ([]byte, error) {
	return _bindataGo, nil
}

func bindataGo() (*asset, error) {
	bytes, err := bindataGoBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bindata.go", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _bmhSecretYaml = []byte(`apiVersion: v1
data:
  password: <pass>
  username: <username>
kind: Secret
metadata:
  name: <secret>
  namespace: openshift-machine-api
type: Opaque
`)

func bmhSecretYamlBytes() ([]byte, error) {
	return _bmhSecretYaml, nil
}

func bmhSecretYaml() (*asset, error) {
	bytes, err := bmhSecretYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bmh-secret.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _bmhYaml = []byte(`apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: <name>
  namespace: openshift-machine-api
spec:
  online: true
  bmc:
    address: exampe
    credentialsName: exampe
    disableCertificateVerification: True
  bootMACAddress: exampe
  hardwareProfile: unknown
  rootDeviceHints:
    deviceName: exampe
`)

func bmhYamlBytes() ([]byte, error) {
	return _bmhYaml, nil
}

func bmhYaml() (*asset, error) {
	bytes, err := bmhYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bmh.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _firmwareCmYaml = []byte(`---
apiVersion: v1
kind: ConfigMap
metadata:
  name: firmware-download
data:
  firmware_url: example_url
  component: example_component
`)

func firmwareCmYamlBytes() ([]byte, error) {
	return _firmwareCmYaml, nil
}

func firmwareCmYaml() (*asset, error) {
	bytes, err := firmwareCmYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "firmware-cm.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _fixturesGo = []byte(`package testdata

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
)

var (
	fixtureDir    string
	fixtureMutex  sync.Map // Map of path -> *sync.Mutex for per-fixture synchronization
)

func init() {
	var err error
	fixtureDir, err = ioutil.TempDir("", "testdata-fixtures-")
	if err != nil {
		panic(fmt.Sprintf("failed to create fixture directory: %v", err))
	}
	// Ensure fixture directory has proper permissions for all users
	if err := os.Chmod(fixtureDir, 0755); err != nil {
		panic(fmt.Sprintf("failed to set fixture directory permissions: %v", err))
	}
}

func FixturePath(elem ...string) string {
	// Validate input elements to prevent path traversal attacks
	for _, e := range elem {
		// Check for absolute paths
		if filepath.IsAbs(e) {
			panic(fmt.Sprintf("absolute path not allowed in fixture path: %s", e))
		}
		// Check for parent directory references
		if e == ".." || strings.Contains(e, ".."+string(filepath.Separator)) || strings.HasPrefix(e, ".."+string(filepath.Separator)) || strings.HasSuffix(e, string(filepath.Separator)+"..") {
			panic(fmt.Sprintf("parent directory references not allowed in fixture path: %s", e))
		}
	}

	relativePath := filepath.Join(elem...)
	targetPath := filepath.Join(fixtureDir, relativePath)

	// Verify the canonical path stays within fixtureDir boundary
	// This prevents traversal attacks even if filepath.Join doesn't fully sanitize
	canonicalTarget, err := filepath.Abs(targetPath)
	if err != nil {
		panic(fmt.Sprintf("failed to get absolute path for %s: %v", targetPath, err))
	}
	canonicalFixtureDir, err := filepath.Abs(fixtureDir)
	if err != nil {
		panic(fmt.Sprintf("failed to get absolute path for fixture dir: %v", err))
	}
	// Check if canonicalTarget is within canonicalFixtureDir
	relPath, err := filepath.Rel(canonicalFixtureDir, canonicalTarget)
	if err != nil || strings.HasPrefix(relPath, "..") {
		panic(fmt.Sprintf("path traversal detected: %s escapes fixture directory", relativePath))
	}

	// Get or create a mutex for this specific fixture path to prevent race conditions
	mutexInterface, _ := fixtureMutex.LoadOrStore(targetPath, &sync.Mutex{})
	mu := mutexInterface.(*sync.Mutex)

	// Lock to ensure only one goroutine extracts this fixture at a time
	mu.Lock()
	defer mu.Unlock()

	// Check again if file exists (might have been created while waiting for lock)
	if _, err := os.Stat(targetPath); err == nil {
		return targetPath
	}

	if err := os.MkdirAll(filepath.Dir(targetPath), 0755); err != nil {
		panic(fmt.Sprintf("failed to create directory for %s: %v", relativePath, err))
	}

	bindataPath := relativePath
	tempDir, err := os.MkdirTemp("", "bindata-extract-")
	if err != nil {
		panic(fmt.Sprintf("failed to create temp directory: %v", err))
	}
	defer os.RemoveAll(tempDir)

	if err := RestoreAsset(tempDir, bindataPath); err != nil {
		if err := RestoreAssets(tempDir, bindataPath); err != nil {
			panic(fmt.Sprintf("failed to restore fixture %s: %v", relativePath, err))
		}
	}

	extractedPath := filepath.Join(tempDir, bindataPath)

	// Set permissions on extracted files/directories before moving
	if err := filepath.Walk(extractedPath, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			if err := os.Chmod(path, 0755); err != nil {
				return fmt.Errorf("failed to chmod directory %s: %v", path, err)
			}
		} else {
			if err := os.Chmod(path, 0644); err != nil {
				return fmt.Errorf("failed to chmod file %s: %v", path, err)
			}
		}
		return nil
	}); err != nil {
		panic(fmt.Sprintf("failed to set permissions on extracted files: %v", err))
	}

	// Use os.Rename to move the extracted file
	// With mutex protection, no race condition should occur
	if err := os.Rename(extractedPath, targetPath); err != nil {
		panic(fmt.Sprintf("failed to move extracted files: %v", err))
	}

	// Ensure final path has correct permissions
	if info, err := os.Stat(targetPath); err == nil {
		if info.IsDir() {
			if err := os.Chmod(targetPath, 0755); err != nil {
				panic(fmt.Sprintf("failed to set final directory permissions: %v", err))
			}
		} else {
			if err := os.Chmod(targetPath, 0644); err != nil {
				panic(fmt.Sprintf("failed to set final file permissions: %v", err))
			}
		}
	}

	return targetPath
}

func CleanupFixtures() error {
	if fixtureDir != "" {
		return os.RemoveAll(fixtureDir)
	}
	return nil
}

func GetFixtureData(elem ...string) ([]byte, error) {
	// Validate input elements to prevent path traversal attacks
	for _, e := range elem {
		// Check for absolute paths
		if filepath.IsAbs(e) {
			return nil, fmt.Errorf("absolute path not allowed in fixture path: %s", e)
		}
		// Check for parent directory references
		if e == ".." || strings.Contains(e, ".."+string(filepath.Separator)) || strings.HasPrefix(e, ".."+string(filepath.Separator)) || strings.HasSuffix(e, string(filepath.Separator)+"..") {
			return nil, fmt.Errorf("parent directory references not allowed in fixture path: %s", e)
		}
	}

	relativePath := filepath.Join(elem...)
	cleanPath := relativePath
	if len(cleanPath) > 0 && cleanPath[0] == '/' {
		cleanPath = cleanPath[1:]
	}
	return Asset(cleanPath)
}

func MustGetFixtureData(elem ...string) []byte {
	data, err := GetFixtureData(elem...)
	if err != nil {
		panic(fmt.Sprintf("failed to get fixture data: %v", err))
	}
	return data
}

func FixtureExists(elem ...string) bool {
	// Validate input elements to prevent path traversal attacks
	for _, e := range elem {
		// Check for absolute paths
		if filepath.IsAbs(e) {
			return false
		}
		// Check for parent directory references
		if e == ".." || strings.Contains(e, ".."+string(filepath.Separator)) || strings.HasPrefix(e, ".."+string(filepath.Separator)) || strings.HasSuffix(e, string(filepath.Separator)+"..") {
			return false
		}
	}

	relativePath := filepath.Join(elem...)
	cleanPath := relativePath
	if len(cleanPath) > 0 && cleanPath[0] == '/' {
		cleanPath = cleanPath[1:]
	}
	_, err := Asset(cleanPath)
	return err == nil
}

func ListFixtures() []string {
	names := AssetNames()
	fixtures := make([]string, 0, len(names))
	for _, name := range names {
		// Filter out generated Go source files (bindata.go, fixtures.go)
		// Include only fixture files (YAML, JSON, etc.)
		if !strings.HasSuffix(name, ".go") {
			fixtures = append(fixtures, name)
		}
	}
	sort.Strings(fixtures)
	return fixtures
}
`)

func fixturesGoBytes() ([]byte, error) {
	return _fixturesGo, nil
}

func fixturesGo() (*asset, error) {
	bytes, err := fixturesGoBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "fixtures.go", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _hostUpdatePolicyYaml = []byte(`apiVersion: metal3.io/v1alpha1
kind: HostUpdatePolicy
metadata:
  name: <BMH name>
  namespace: openshift-machine-api
spec:
  firmwareSettings: onReboot
  firmwareUpdates: onReboot
`)

func hostUpdatePolicyYamlBytes() ([]byte, error) {
	return _hostUpdatePolicyYaml, nil
}

func hostUpdatePolicyYaml() (*asset, error) {
	bytes, err := hostUpdatePolicyYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "host-update-policy.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _nginxFirmwareYaml = []byte(`---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-no-ssl
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;

        location / {
            root /usr/share/nginx/html;
            autoindex on;
        }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  nodeSelector:
    nginx-node: "true"
  volumes:
    - name: firmware-dir
      emptyDir: {}  # Empty directory to hold the downloaded firmware files
    - name: firmware-config
      configMap:
        name: firmware-download
    - name: nginx-conf
      configMap:
        name: nginx-no-ssl
    - name: nginx-cache
      emptyDir: {}
    - name: nginx-run
      emptyDir: {}
    - name: init-tmp
      emptyDir: {}
  initContainers:
    - name: init-download-firmware
      image: ghcr.io/crazy-max/7zip
      imagePullPolicy: IfNotPresent
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      env:
        - name: FIRMWARE_URL
          valueFrom:
            configMapKeyRef:
              name: firmware-download
              key: firmware_url
        - name: COMPONENT
          valueFrom:
            configMapKeyRef:
              name: firmware-download
              key: component
      command:
      - /bin/sh
      - -c
      - |
        set -e

        # Validate FIRMWARE_URL scheme and hostname
        # Extract scheme
        url_scheme=$(echo "${FIRMWARE_URL}" | sed -n 's|^\([^:]*\)://.*|\1|p')
        if [ "${url_scheme}" != "http" ] && [ "${url_scheme}" != "https" ]; then
          echo "ERROR: Invalid URL scheme '${url_scheme}'. Only http and https are allowed." >&2
          exit 1
        fi

        # Extract hostname (with optional port, may include userinfo)
        url_authority=$(echo "${FIRMWARE_URL}" | sed -n 's|^[^:]*://\([^/]*\).*|\1|p')

        # Strip userinfo (credentials) from authority to get clean host
        # Format: [user[:pass]@]host[:port] -> host[:port]
        url_host=$(echo "${url_authority}" | sed 's|^.*@||')

        # Strip port from hostname for validation (e.g., example.com:8080 -> example.com)
        url_host_no_port=$(echo "${url_host}" | sed 's/:[0-9]*$//')

        # Log redacted URL (scheme and host only, no credentials or query params)
        echo "Validating FIRMWARE_URL: ${url_scheme}://${url_host}/..."

        # Allowlist of expected firmware hosts
        allowed_hosts="downloads.dell.com support.hpe.com fwupd.org cdn.redhat.com quay.io"

        # Check if hostname is in allowlist (exact string match, not regex)
        host_allowed=0
        for allowed in ${allowed_hosts}; do
          if [ "${url_host_no_port}" = "${allowed}" ]; then
            host_allowed=1
            break
          fi
        done

        if [ ${host_allowed} -eq 0 ]; then
          echo "ERROR: Hostname '${url_host_no_port}' is not in the allowlist: ${allowed_hosts}" >&2
          exit 1
        fi

        echo "URL validation passed: scheme=${url_scheme}, host=${url_host_no_port}"

        # Proceed with download (disable xtrace to prevent credential exposure)
        set +x
        rm -f /fw/*
        wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36" \
          --directory-prefix=/fw \
          -- "${FIRMWARE_URL}"
        set -x

        if [ "${COMPONENT}" != "nic" ]; then
          7za e /fw/* -o/fw
        fi
      volumeMounts:
        - name: firmware-config
          mountPath: /config
        - name: firmware-dir
          mountPath: /fw
        - name: init-tmp
          mountPath: /tmp
  containers:
    - name: nginx
      image: quay.io/openshifttest/nginx-alpine:armbm
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "200m"
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 5
      volumeMounts:
        - name: firmware-dir
          mountPath: /usr/share/nginx/html
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
`)

func nginxFirmwareYamlBytes() ([]byte, error) {
	return _nginxFirmwareYaml, nil
}

func nginxFirmwareYaml() (*asset, error) {
	bytes, err := nginxFirmwareYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "nginx-firmware.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"bindata.go":              bindataGo,
	"bmh-secret.yaml":         bmhSecretYaml,
	"bmh.yaml":                bmhYaml,
	"firmware-cm.yaml":        firmwareCmYaml,
	"fixtures.go":             fixturesGo,
	"host-update-policy.yaml": hostUpdatePolicyYaml,
	"nginx-firmware.yaml":     nginxFirmwareYaml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"bindata.go":              {bindataGo, map[string]*bintree{}},
	"bmh-secret.yaml":         {bmhSecretYaml, map[string]*bintree{}},
	"bmh.yaml":                {bmhYaml, map[string]*bintree{}},
	"firmware-cm.yaml":        {firmwareCmYaml, map[string]*bintree{}},
	"fixtures.go":             {fixturesGo, map[string]*bintree{}},
	"host-update-policy.yaml": {hostUpdatePolicyYaml, map[string]*bintree{}},
	"nginx-firmware.yaml":     {nginxFirmwareYaml, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
