// Code generated by go-bindata. (@generated) DO NOT EDIT.

//Package testdata generated by go-bindata.// sources:
// testdata/bindata.go
// testdata/fixtures.go
// testdata/nginx-ingress.yaml
// testdata/nginx-iso.yaml
// testdata/non-bootable-iso.yaml
package testdata

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _bindataGo = []byte(``)

func bindataGoBytes() ([]byte, error) {
	return _bindataGo, nil
}

func bindataGo() (*asset, error) {
	bytes, err := bindataGoBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "bindata.go", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _fixturesGo = []byte(`package testdata

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
)

var (
	fixtureDir    string
	fixtureMutex  sync.Map // Map of path -> *sync.Mutex for per-fixture synchronization
)

func init() {
	var err error
	fixtureDir, err = ioutil.TempDir("", "testdata-fixtures-")
	if err != nil {
		panic(fmt.Sprintf("failed to create fixture directory: %v", err))
	}
	// Ensure fixture directory has proper permissions for all users
	if err := os.Chmod(fixtureDir, 0755); err != nil {
		panic(fmt.Sprintf("failed to set fixture directory permissions: %v", err))
	}
}

func FixturePath(elem ...string) string {
	// Validate input elements to prevent path traversal attacks
	for _, e := range elem {
		// Check for absolute paths
		if filepath.IsAbs(e) {
			panic(fmt.Sprintf("absolute path not allowed in fixture path: %s", e))
		}
		// Check for parent directory references
		if e == ".." || strings.Contains(e, ".."+string(filepath.Separator)) || strings.HasPrefix(e, ".."+string(filepath.Separator)) || strings.HasSuffix(e, string(filepath.Separator)+"..") {
			panic(fmt.Sprintf("parent directory references not allowed in fixture path: %s", e))
		}
	}

	relativePath := filepath.Join(elem...)
	targetPath := filepath.Join(fixtureDir, relativePath)

	// Verify the canonical path stays within fixtureDir boundary
	// This prevents traversal attacks even if filepath.Join doesn't fully sanitize
	canonicalTarget, err := filepath.Abs(targetPath)
	if err != nil {
		panic(fmt.Sprintf("failed to get absolute path for %s: %v", targetPath, err))
	}
	canonicalFixtureDir, err := filepath.Abs(fixtureDir)
	if err != nil {
		panic(fmt.Sprintf("failed to get absolute path for fixture dir: %v", err))
	}
	// Check if canonicalTarget is within canonicalFixtureDir
	relPath, err := filepath.Rel(canonicalFixtureDir, canonicalTarget)
	if err != nil || strings.HasPrefix(relPath, "..") {
		panic(fmt.Sprintf("path traversal detected: %s escapes fixture directory", relativePath))
	}

	// Get or create a mutex for this specific fixture path to prevent race conditions
	mutexInterface, _ := fixtureMutex.LoadOrStore(targetPath, &sync.Mutex{})
	mu := mutexInterface.(*sync.Mutex)

	// Lock to ensure only one goroutine extracts this fixture at a time
	mu.Lock()
	defer mu.Unlock()

	// Check again if file exists (might have been created while waiting for lock)
	if _, err := os.Stat(targetPath); err == nil {
		return targetPath
	}

	if err := os.MkdirAll(filepath.Dir(targetPath), 0755); err != nil {
		panic(fmt.Sprintf("failed to create directory for %s: %v", relativePath, err))
	}

	bindataPath := relativePath
	tempDir, err := os.MkdirTemp("", "bindata-extract-")
	if err != nil {
		panic(fmt.Sprintf("failed to create temp directory: %v", err))
	}
	defer os.RemoveAll(tempDir)

	if err := RestoreAsset(tempDir, bindataPath); err != nil {
		if err := RestoreAssets(tempDir, bindataPath); err != nil {
			panic(fmt.Sprintf("failed to restore fixture %s: %v", relativePath, err))
		}
	}

	extractedPath := filepath.Join(tempDir, bindataPath)

	// Set permissions on extracted files/directories before moving
	if err := filepath.Walk(extractedPath, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			if err := os.Chmod(path, 0755); err != nil {
				return fmt.Errorf("failed to chmod directory %s: %v", path, err)
			}
		} else {
			if err := os.Chmod(path, 0644); err != nil {
				return fmt.Errorf("failed to chmod file %s: %v", path, err)
			}
		}
		return nil
	}); err != nil {
		panic(fmt.Sprintf("failed to set permissions on extracted files: %v", err))
	}

	// Use os.Rename to move the extracted file
	// With mutex protection, no race condition should occur
	if err := os.Rename(extractedPath, targetPath); err != nil {
		panic(fmt.Sprintf("failed to move extracted files: %v", err))
	}

	// Ensure final path has correct permissions
	if info, err := os.Stat(targetPath); err == nil {
		if info.IsDir() {
			if err := os.Chmod(targetPath, 0755); err != nil {
				panic(fmt.Sprintf("failed to set final directory permissions: %v", err))
			}
		} else {
			if err := os.Chmod(targetPath, 0644); err != nil {
				panic(fmt.Sprintf("failed to set final file permissions: %v", err))
			}
		}
	}

	return targetPath
}

func CleanupFixtures() error {
	if fixtureDir != "" {
		return os.RemoveAll(fixtureDir)
	}
	return nil
}

func GetFixtureData(elem ...string) ([]byte, error) {
	relativePath := filepath.Join(elem...)
	cleanPath := relativePath
	if len(cleanPath) > 0 && cleanPath[0] == '/' {
		cleanPath = cleanPath[1:]
	}
	return Asset(cleanPath)
}

func MustGetFixtureData(elem ...string) []byte {
	data, err := GetFixtureData(elem...)
	if err != nil {
		panic(fmt.Sprintf("failed to get fixture data: %v", err))
	}
	return data
}

func FixtureExists(elem ...string) bool {
	relativePath := filepath.Join(elem...)
	cleanPath := relativePath
	if len(cleanPath) > 0 && cleanPath[0] == '/' {
		cleanPath = cleanPath[1:]
	}
	_, err := Asset(cleanPath)
	return err == nil
}

func ListFixtures() []string {
	names := AssetNames()
	fixtures := make([]string, 0, len(names))
	for _, name := range names {
		// Filter out generated Go source files (bindata.go, fixtures.go)
		// Include only fixture files (YAML, JSON, etc.)
		if !strings.HasSuffix(name, ".go") {
			fixtures = append(fixtures, name)
		}
	}
	sort.Strings(fixtures)
	return fixtures
}
`)

func fixturesGoBytes() ([]byte, error) {
	return _fixturesGo, nil
}

func fixturesGo() (*asset, error) {
	bytes, err := fixturesGoBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "fixtures.go", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _nginxIngressYaml = []byte(`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sample-entry
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-network-policy
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from pods in the same namespace
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
  # Allow traffic from OpenShift ingress/router pods
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
    ports:
    - protocol: TCP
      port: 8080
  egress:
  # Allow DNS queries
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-dns
    ports:
    - protocol: UDP
      port: 53
  # Allow access to Kubernetes API server
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: openshift-kube-apiserver
    ports:
    - protocol: TCP
      port: 443
  # Allow outbound traffic within the same namespace
  - to:
    - podSelector: {}
`)

func nginxIngressYamlBytes() ([]byte, error) {
	return _nginxIngressYaml, nil
}

func nginxIngressYaml() (*asset, error) {
	bytes, err := nginxIngressYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "nginx-ingress.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _nginxIsoYaml = []byte(`---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-iso-configmap
data:
  iso.gz.b64: |
    H4sICLBAhWYAA25iLmlzbwDt201rE0EYAOCJFowBhSKSHpeeVDCdfJAQPIVkm27Nh2RTsEcL3sRcPPqf/ImaTRpEa9NLjRKeh92d3Zl3d2dhmGUGJgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoNQfxFgvhVE2uXif3K4/mE3HW8o3z/v2S7Llvcut2EO5HCrrrMqzn8XPi8NxqK6vqqFcJOXw9dHDJ0+PDx5s7t9SIXZgmE6yfJqNe8M0WZ4k3XY7npyd5slpNkrzy3yejpP+LO3Np7PkRf9lUu92m0lau5xeTIaD3ijdZHZeN2JsJ+e1d2lvlk8nJ+e1vH+WjZatcriKKYqLmE7REN9m82Se9rY1x7+jERut2InNerPeasUYD25kxN+EGxGlsPNq81+5j24b7sX36/8/AAAAsL9Kqzl2438AAADYZ6uRf9UEAAAAAOyzu9fY3RlRehWO1hFHh+v08DoirCMez9LeYJzW3tR3+mkAwC0mi8/J1WLx5cPVp4/FEu7Kv64QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8wQ9XmJ9tAHgFAA==

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  nodeSelector:
    nginx-node: "true"
  volumes:
    - name: iso-dir
      emptyDir: {}  # Empty directory to hold the decoded ISO
    - name: iso-config
      configMap:
        name: nginx-iso-configmap
  initContainers:
    - name: init-decode-iso
      image: quay.io/openshifttest/busybox:latest
      command: ['sh', '-c', 'base64 -d /config/iso.gz.b64 | gunzip > /iso/non-bootable.iso && mkdir -p /iso/data && echo "test" > /iso/data/1K']
      volumeMounts:
        - name: iso-config
          mountPath: /config
        - name: iso-dir
          mountPath: /iso
  containers:
    - name: nginx
      image: quay.io/openshifttest/nginx-alpine:latest
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
      volumeMounts:
        - name: iso-dir
          mountPath: /data/http
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
`)

func nginxIsoYamlBytes() ([]byte, error) {
	return _nginxIsoYaml, nil
}

func nginxIsoYaml() (*asset, error) {
	bytes, err := nginxIsoYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "nginx-iso.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _nonBootableIsoYaml = []byte(`apiVersion: metal3.io/v1alpha1
kind: DataImage
metadata:
  name: example.dataimage
spec:
  url: example.url
`)

func nonBootableIsoYamlBytes() ([]byte, error) {
	return _nonBootableIsoYaml, nil
}

func nonBootableIsoYaml() (*asset, error) {
	bytes, err := nonBootableIsoYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "non-bootable-iso.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"bindata.go":            bindataGo,
	"fixtures.go":           fixturesGo,
	"nginx-ingress.yaml":    nginxIngressYaml,
	"nginx-iso.yaml":        nginxIsoYaml,
	"non-bootable-iso.yaml": nonBootableIsoYaml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"bindata.go":            {bindataGo, map[string]*bintree{}},
	"fixtures.go":           {fixturesGo, map[string]*bintree{}},
	"nginx-ingress.yaml":    {nginxIngressYaml, map[string]*bintree{}},
	"nginx-iso.yaml":        {nginxIsoYaml, map[string]*bintree{}},
	"non-bootable-iso.yaml": {nonBootableIsoYaml, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
