/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	metal3iov1alpha1 "github.com/openshift/cluster-baremetal-operator/apis/metal3.io/v1alpha1"
	internalinterfaces "github.com/openshift/cluster-baremetal-operator/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/openshift/cluster-baremetal-operator/client/listers/metal3.io/v1alpha1"
	versioned "github.com/openshift/cluster-baremetal-operator/client/versioned"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ProvisioningInformer provides access to a shared informer and lister for
// Provisionings.
type ProvisioningInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ProvisioningLister
}

type provisioningInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewProvisioningInformer constructs a new informer for Provisioning type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewProvisioningInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredProvisioningInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredProvisioningInformer constructs a new informer for Provisioning type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredProvisioningInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Metal3V1alpha1().Provisionings().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Metal3V1alpha1().Provisionings().Watch(context.TODO(), options)
			},
		},
		&metal3iov1alpha1.Provisioning{},
		resyncPeriod,
		indexers,
	)
}

func (f *provisioningInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredProvisioningInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *provisioningInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&metal3iov1alpha1.Provisioning{}, f.defaultInformer)
}

func (f *provisioningInformer) Lister() v1alpha1.ProvisioningLister {
	return v1alpha1.NewProvisioningLister(f.Informer().GetIndexer())
}
