namespace: openshift-machine-api

bases:
- ../../crd
- ../../rbac
- ../../cluster-baremetal-operator
- ../../cluster-baremetal-operator-hostedcluster
- ../../webhook
- ../../prometheus

patchesStrategicMerge:
  # Protect the /metrics endpoint by putting it behind auth.
  # Only one of manager_auth_proxy_patch.yaml and
  # manager_prometheus_metrics_patch.yaml should be enabled.
- manager_auth_proxy_patch.yaml
  # If you want your controller-manager to expose the /metrics
  # endpoint w/o any authn/z, uncomment the following line and
  # comment manager_auth_proxy_patch.yaml.
  # Only one of manager_auth_proxy_patch.yaml and
  # manager_prometheus_metrics_patch.yaml should be enabled.
#- manager_prometheus_metrics_patch.yaml

# [WEBHOOK] To enable some optional webhooks, uncomment all the sections with [WEBHOOK] prefix, including the one in crd/kustomization.yaml
- manager_webhook_patch.yaml
- manager_webhook_patch_hostedcluster.yaml
- webhookcainjection_patch.yaml

patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: Role
    name: cluster-baremetal-operator-pull-secret
  path: pull_secret_namespace_patch.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: cluster-baremetal-operator-pull-secret
  path: pull_secret_namespace_patch.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: Role
    name: cluster-baremetal-operator-cluster-config
  path: cluster_config_namespace_patch.yaml
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: RoleBinding
    name: cluster-baremetal-operator-cluster-config
  path: cluster_config_namespace_patch.yaml
